apiVersion: apps/v1
kind: Deployment
metadata:
  name: wapstore-modelo-deployment
  namespace: local-uappi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wapstore
  template:
    metadata:
      annotations:
        # A alteração nesta anotação fará com que o Kubernetes reinicie os pods.
        # Você deve atualizar o valor desta anotação (ex: para um novo checksum dos secrets)
        # toda vez que alterar o 'secret-db-php.yaml' ou 'secret-php-config.yaml'
        # para forçar o reinício da aplicação.
        checksum/config: "initial-checksum"
      labels:
        app: wapstore
    spec:
      containers:
      - name: wapstore
        image: wapstore:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "sua-string-de-conexao-com-o-banco"
        - name: PORT
          value: "80"
        volumeMounts:
        - name: php-ini
          mountPath: /etc/php/7.4/apache2/php.ini
          subPath: php.ini
        - name: php-ini
          mountPath: /etc/php/7.4/cli/php.ini
          subPath: php.ini
        - name: php-ini
          mountPath: /etc/php/7.4/fpm/php.ini
          subPath: php.ini
        - name: db-config
          mountPath: /var/www/html/modelo/db.php
          subPath: db.php
        lifecycle:
          #postStart:
            #exec:
              #command:
              #- "/bin/sh"
              #- "-c"
              #- "cp /tmp/db-config/db.php /var/www/html/modelo/db.php"
      volumes:
      - name: php-ini
        secret:
          secretName: wapstore-modelo-php-config
      - name: db-config
        secret:
          secretName: wapstore-modelo-db-config

